import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "~/styles/globals.css";
import Providers from "./Extra/Providers";
import Navbar from "./Extra/components/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={`${GeistSans.className} dark`}>
			<body>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
